// Datos mock del ERP de comunidad (ANTARES). Espejo del HTML de referencia.
// Toda la información es estática; el ErpProvider mantiene el estado mutable.

import type {
  CommunityGroup,
  CommunityMember,
  DiagnosticStat,
  ErpPost,
  FeedItem,
  NetworkChannel,
  Recognition,
  RegionStat,
  RiskLevel,
  StreakRank,
} from "./types";

export const LEVEL_ICON: Record<string, string> = {
  Bienestar: "💎",
  Disciplinado: "🔥",
  Constante: "💪",
  Iniciado: "🌿",
  Explorador: "🌱",
};

export const RISK_ICON: Record<string, string> = {
  Alto: "🔴",
  Medio: "🟠",
  Bajo: "🟡",
};

export const mockMembers: CommunityMember[] = [
  {
    id: "m-carolina",
    firstName: "Carolina",
    lastName: "Mendoza",
    diagnosis: "DM2",
    region: "Miami",
    week: 12,
    posts: 142,
    comments: 320,
    reactions: 980,
    xp: 4820,
    streak: 45,
    level: "Bienestar",
    status: "Activo",
    daysSincePost: 0,
    lastPost: "Hace 3 min",
    topRank: 1,
    courses: 7,
    shared: true,
  },
  {
    id: "m-andres",
    firstName: "Andrés",
    lastName: "Cárdenas",
    diagnosis: "DM2+HTA",
    region: "NY",
    week: 10,
    posts: 87,
    comments: 210,
    reactions: 640,
    xp: 3940,
    streak: 38,
    level: "Disciplinado",
    status: "Activo",
    daysSincePost: 0,
    lastPost: "Hace 1 h",
    topRank: 2,
    courses: 5,
    shared: true,
  },
  {
    id: "m-valentina",
    firstName: "Valentina",
    lastName: "Ríos",
    diagnosis: "Obesidad",
    region: "Barranquilla",
    week: 8,
    posts: 64,
    comments: 150,
    reactions: 480,
    xp: 3210,
    streak: 31,
    level: "Constante",
    status: "Activo",
    daysSincePost: 0,
    lastPost: "Hace 2 h",
    topRank: 3,
    courses: 4,
    shared: true,
  },
  {
    id: "m-jorge",
    firstName: "Jorge",
    lastName: "Herrera",
    diagnosis: "DM2",
    region: "Miami",
    week: 6,
    posts: 42,
    comments: 98,
    reactions: 310,
    xp: 2180,
    streak: 22,
    level: "Iniciado",
    status: "Activo",
    daysSincePost: 0,
    lastPost: "Hace 4 h",
    courses: 3,
    shared: false,
  },
  {
    id: "m-maria",
    firstName: "María",
    lastName: "González",
    diagnosis: "Obesidad",
    region: "Bogotá",
    week: 5,
    posts: 28,
    comments: 70,
    reactions: 220,
    xp: 1760,
    streak: 18,
    level: "Explorador",
    status: "Activo",
    daysSincePost: 0,
    lastPost: "Hace 6 h",
    courses: 2,
    shared: false,
  },
  {
    id: "m-luis",
    firstName: "Luis",
    lastName: "Pérez",
    diagnosis: "DM2",
    region: "Miami",
    week: 9,
    posts: 17,
    comments: 30,
    reactions: 90,
    xp: 800,
    streak: 0,
    level: "Explorador",
    status: "Inactivo",
    daysSincePost: 12,
    lastPost: "Hace 12 días",
  },
  {
    id: "m-rosa",
    firstName: "Rosa",
    lastName: "García",
    diagnosis: "Obesidad",
    region: "Barranquilla",
    week: 7,
    posts: 21,
    comments: 44,
    reactions: 110,
    xp: 940,
    streak: 0,
    level: "Explorador",
    status: "Inactivo",
    daysSincePost: 9,
    lastPost: "Hace 9 días",
  },
  {
    id: "m-manuel",
    firstName: "Manuel",
    lastName: "Suárez",
    diagnosis: "DM2+HTA",
    region: "Bogotá",
    week: 11,
    posts: 33,
    comments: 60,
    reactions: 150,
    xp: 1280,
    streak: 0,
    level: "Iniciado",
    status: "Inactivo",
    daysSincePost: 8,
    lastPost: "Hace 8 días",
  },
  {
    id: "m-teresa",
    firstName: "Teresa",
    lastName: "Mora",
    diagnosis: "Obesidad",
    region: "Orlando",
    week: 4,
    posts: 12,
    comments: 20,
    reactions: 60,
    xp: 560,
    streak: 0,
    level: "Explorador",
    status: "Inactivo",
    daysSincePost: 7,
    lastPost: "Hace 7 días",
  },
  {
    id: "m-hector",
    firstName: "Héctor",
    lastName: "Blanco",
    diagnosis: "DM2",
    region: "NY",
    week: 8,
    posts: 25,
    comments: 38,
    reactions: 95,
    xp: 1020,
    streak: 0,
    level: "Iniciado",
    status: "Inactivo",
    daysSincePost: 7,
    lastPost: "Hace 7 días",
  },
];

export const mockPosts: ErpPost[] = [
  {
    id: "p-1",
    author: "Carolina Mendoza",
    authorId: "m-carolina",
    type: "Logro",
    destination: "Todas las comunidades",
    body: "¡Llegué a 45 días de racha! Gracias a todos por el apoyo en el reto de caminata 🏆",
    pinned: true,
    pinnedOrder: 0,
    createdAt: "Hace 2 h",
    reactions: 212,
    comments: 48,
    views: 1840,
    imageUrl: null,
    mediaType: null,
    poll: null,
    commentsList: [],
  },
  {
    id: "p-2",
    author: "Dr. Arturo Godoy",
    authorId: "m-doctor",
    type: "Imagen",
    destination: "Solo activos",
    body: "Nuevas teleconsultas disponibles esta semana. Agenda tu cita de seguimiento 💊",
    pinned: true,
    pinnedOrder: 1,
    createdAt: "Hace 1 d",
    reactions: 134,
    comments: 22,
    views: 980,
    imageUrl: null,
    mediaType: null,
    poll: null,
    commentsList: [],
  },
  {
    id: "p-3",
    author: "Valentina Ríos",
    authorId: "m-valentina",
    type: "Texto",
    destination: "Comunidad ADRED",
    body: "¡Bienvenidos a la comunidad! Comparte tu primer objetivo de la semana 👋",
    pinned: true,
    pinnedOrder: 2,
    createdAt: "Hace 11 d",
    reactions: 89,
    comments: 15,
    views: 620,
    imageUrl: null,
    mediaType: null,
    poll: null,
    commentsList: [],
  },
  {
    id: "p-4",
    author: "Carolina Mendoza",
    authorId: "m-carolina",
    type: "Imagen",
    destination: "Comunidad ADRED",
    body: "Mi desayuno saludable de hoy 🥗",
    pinned: false,
    pinnedOrder: 0,
    createdAt: "Hace 3 h",
    reactions: 56,
    comments: 9,
    views: 320,
    imageUrl: null,
    mediaType: null,
    poll: null,
    commentsList: [],
  },
  {
    id: "p-5",
    author: "Andrés Cárdenas",
    authorId: "m-andres",
    type: "Logro",
    destination: "Comunidad ADRED",
    body: "38 días de racha y contando 🔥",
    pinned: true,
    pinnedOrder: 3,
    createdAt: "Hace 5 h",
    reactions: 71,
    comments: 12,
    views: 410,
    imageUrl: null,
    mediaType: null,
    poll: null,
    commentsList: [],
  },
  {
    id: "p-6",
    author: "Valentina Ríos",
    authorId: "m-valentina",
    type: "Texto",
    destination: "Comunidad ADRED",
    body: "Tip de la semana: caminar 30 minutos después de comer ayuda a regular la glucosa.",
    pinned: false,
    pinnedOrder: 0,
    createdAt: "Hace 8 h",
    reactions: 44,
    comments: 7,
    views: 260,
    imageUrl: null,
    mediaType: null,
    poll: null,
    commentsList: [],
  },
  {
    id: "p-7",
    author: "Jorge Herrera",
    authorId: "m-jorge",
    type: "Video",
    destination: "Comunidad ADRED",
    body: "Rutina de estiramientos en casa 🎬",
    pinned: false,
    pinnedOrder: 0,
    createdAt: "Hace 1 d",
    reactions: 38,
    comments: 5,
    views: 190,
    imageUrl: null,
    mediaType: null,
    poll: null,
    commentsList: [],
  },
];

export const mockFeed: FeedItem[] = [
  {
    id: "f-1",
    member: "Carolina Mendoza",
    memberId: "m-carolina",
    kind: "foto",
    description: "publicó una foto en Comunidad ADRED",
    time: "Hace 3 min",
  },
  {
    id: "f-2",
    member: "Andrés Cárdenas",
    memberId: "m-andres",
    kind: "hito",
    description: "alcanzó un hito: 38 días de racha 🔥",
    time: "Hace 18 min",
  },
  {
    id: "f-3",
    member: "Valentina Ríos",
    memberId: "m-valentina",
    kind: "comentario",
    description: "comentó en tu publicación",
    time: "Hace 41 min",
  },
  {
    id: "f-4",
    member: "Jorge Herrera",
    memberId: "m-jorge",
    kind: "grupo",
    description: "se unió al grupo Reto caminata 30 días",
    time: "Hace 1 h",
  },
  {
    id: "f-5",
    member: "María González",
    memberId: "m-maria",
    kind: "nutriobiotico",
    description: "tomó su nutriobiótico y ganó +20 XP",
    time: "Hace 2 h",
    xp: 20,
  },
  {
    id: "f-6",
    member: "Carolina Mendoza",
    memberId: "m-carolina",
    kind: "publicacion",
    description: "fijó una publicación en Todas las comunidades",
    time: "Hace 2 h",
  },
  {
    id: "f-7",
    member: "Andrés Cárdenas",
    memberId: "m-andres",
    kind: "racha",
    description: "mantiene su racha de 38 días 🔥",
    time: "Hace 3 h",
  },
  {
    id: "f-8",
    member: "Valentina Ríos",
    memberId: "m-valentina",
    kind: "comentario",
    description: "respondió en el grupo Apoyo emocional",
    time: "Hace 4 h",
  },
];

export const mockGroups: CommunityGroup[] = [
  {
    id: "g-1",
    name: "Reto caminata 30 días",
    members: 47,
    posts: 312,
    type: "Reto",
    lastActivity: "22 ago",
  },
  {
    id: "g-2",
    name: "Apoyo emocional",
    members: 31,
    posts: 198,
    type: "Apoyo",
    lastActivity: "18 ago",
  },
  {
    id: "g-3",
    name: "Cocina saludable",
    members: 28,
    posts: 247,
    type: "Nutrición",
    lastActivity: "15 ago",
  },
  {
    id: "g-4",
    name: "Chat ANTARES general",
    members: 284,
    posts: 1840,
    type: "General",
    lastActivity: "1 ago",
  },
  {
    id: "g-5",
    name: "Comunidad ADRED",
    members: 284,
    posts: 1420,
    type: "Principal",
    lastActivity: "1 ago",
  },
];

export const mockRecognitions: Recognition[] = [
  {
    id: "r-1",
    member: "Carolina Mendoza",
    memberId: "m-carolina",
    typeLabel: "Miembro del mes",
    xp: 200,
    status: "Enviado",
    date: "20 ago",
  },
  {
    id: "r-2",
    member: "Andrés Cárdenas",
    memberId: "m-andres",
    typeLabel: "Racha destacada",
    xp: 150,
    status: "Enviado",
    date: "19 ago",
  },
  {
    id: "r-3",
    member: "Valentina Ríos",
    memberId: "m-valentina",
    typeLabel: "Adherencia NB",
    xp: 100,
    status: "Enviado",
    date: "18 ago",
  },
  {
    id: "r-4",
    member: "Jorge Herrera",
    memberId: "m-jorge",
    typeLabel: "Publicación top",
    xp: 75,
    status: "Enviado",
    date: "17 ago",
  },
];

export const mockNetworks: NetworkChannel[] = [
  {
    id: "n-1",
    name: "TikTok",
    followers: "48.2K",
    color: "#0EA5E9",
    growth: [
      { month: "Abr", value: 31000 },
      { month: "May", value: 36000 },
      { month: "Jun", value: 41000 },
      { month: "Jul", value: 45000 },
      { month: "Ago", value: 48200 },
    ],
  },
  {
    id: "n-2",
    name: "Instagram",
    followers: "23.7K",
    color: "#D946EF",
    growth: [
      { month: "Abr", value: 18000 },
      { month: "May", value: 20000 },
      { month: "Jun", value: 21500 },
      { month: "Jul", value: 22800 },
      { month: "Ago", value: 23700 },
    ],
  },
  {
    id: "n-3",
    name: "Facebook",
    followers: "15.4K",
    color: "#2563EB",
    growth: [
      { month: "Abr", value: 11000 },
      { month: "May", value: 12200 },
      { month: "Jun", value: 13500 },
      { month: "Jul", value: 14700 },
      { month: "Ago", value: 15400 },
    ],
  },
  {
    id: "n-4",
    name: "YouTube",
    followers: "8.1K",
    color: "#DC2626",
    growth: [
      { month: "Abr", value: 5000 },
      { month: "May", value: 6000 },
      { month: "Jun", value: 6900 },
      { month: "Jul", value: 7500 },
      { month: "Ago", value: 8100 },
    ],
  },
  {
    id: "n-5",
    name: "WhatsApp",
    followers: "284",
    color: "#059669",
    growth: [
      { month: "Abr", value: 210 },
      { month: "May", value: 235 },
      { month: "Jun", value: 255 },
      { month: "Jul", value: 272 },
      { month: "Ago", value: 284 },
    ],
  },
];

export const mockRegions: RegionStat[] = [
  { region: "Miami", members: 5, postsPerWeek: 7.8, percent: 13 },
  { region: "NY", members: 5, postsPerWeek: 6.4, percent: 13 },
  { region: "Barranquilla", members: 5, postsPerWeek: 8.2, percent: 13 },
  { region: "Orlando", members: 5, postsPerWeek: 5.9, percent: 13 },
  { region: "Houston", members: 4, postsPerWeek: 6.8, percent: 10 },
  { region: "Dallas", members: 4, postsPerWeek: 6.1, percent: 10 },
  { region: "Atlanta", members: 4, postsPerWeek: 5.7, percent: 10 },
  { region: "Seattle", members: 4, postsPerWeek: 5.2, percent: 10 },
  { region: "Denver", members: 4, postsPerWeek: 4.9, percent: 10 },
];

export const mockDiagnostics: DiagnosticStat[] = [
  {
    diagnosis: "DM2",
    members: 148,
    trend: "+8%",
    barWidth: 52,
    postsPerWeek: 8.4,
    avgStreak: 18,
    avgXp: 2600,
    adherence: 78,
  },
  {
    diagnosis: "Obesidad",
    members: 89,
    trend: "+15%",
    barWidth: 31,
    postsPerWeek: 6.2,
    avgStreak: 14,
    avgXp: 1900,
    adherence: 64,
  },
  {
    diagnosis: "DM2+HTA",
    members: 31,
    trend: "=0%",
    barWidth: 11,
    postsPerWeek: 9.1,
    avgStreak: 21,
    avgXp: 3100,
    adherence: 82,
  },
  {
    diagnosis: "Prediabetes",
    members: 16,
    trend: "+3%",
    barWidth: 6,
    postsPerWeek: 5.4,
    avgStreak: 11,
    avgXp: 1400,
    adherence: 71,
  },
];

export const mockStreaks: StreakRank[] = [
  { id: "s-1", member: "Carolina Mendoza", memberId: "m-carolina", streak: 45, goal: 45, shared: true, xp: 8500 },
  { id: "s-2", member: "Andrés Cárdenas", memberId: "m-andres", streak: 38, goal: 40, shared: true, xp: 6200 },
  { id: "s-3", member: "Valentina Ríos", memberId: "m-valentina", streak: 31, goal: 31, shared: true, xp: 4800 },
  { id: "s-4", member: "Jorge Herrera", memberId: "m-jorge", streak: 22, goal: 30, shared: false, xp: 3200 },
  { id: "s-5", member: "María González", memberId: "m-maria", streak: 18, goal: 20, shared: false, xp: 2400 },
  { id: "s-6", member: "Patricia S.", memberId: "m-patricia", streak: 14, goal: 21, shared: false, xp: 1800 },
  { id: "s-7", member: "Roberto L.", memberId: "m-roberto", streak: 11, goal: 15, shared: false, xp: 1200 },
];

// --- Datos de gráficos ---

export const activitySeries = Array.from({ length: 30 }, (_, i) => ({
  dia: `${i + 1}`,
  posts: 40 + Math.round(30 * Math.sin(i / 3)) + (i % 5) * 4,
  comentarios: 60 + Math.round(25 * Math.cos(i / 4)) + (i % 4) * 6,
  reacciones: 120 + Math.round(50 * Math.sin(i / 2)) + (i % 3) * 10,
}));

export const postTypeData = [
  { name: "Texto", value: 38 },
  { name: "Foto", value: 31 },
  { name: "Video", value: 18 },
  { name: "Logro", value: 9 },
  { name: "Encuesta", value: 4 },
];

export const peakHoursData = Array.from({ length: 24 }, (_, h) => ({
  hora: `${h}:00`,
  valor:
    h >= 7 && h <= 9
      ? 80 + (h - 7) * 10
      : h >= 12 && h <= 14
        ? 95 + (h - 12) * 8
        : h >= 18 && h <= 21
          ? 120 + (h - 18) * 12
          : 20 + (h % 6) * 4,
}));

export const diagnosisParticipation = [
  { subject: "DM2", value: 71, fullMark: 100 },
  { subject: "Obesidad", value: 42, fullMark: 100 },
  { subject: "DM2+HTA", value: 84, fullMark: 100 },
  { subject: "Prediabetes", value: 54, fullMark: 100 },
];

export const inactivityData = [
  { range: "1-3 d", value: 14 },
  { range: "4-6 d", value: 22 },
  { range: "7-9 d", value: 8 },
  { range: "10-14 d", value: 4 },
  { range: "15+ d", value: 2 },
];

export const streakDistribution = [
  { range: "1-6 d", value: 68 },
  { range: "7-10 d", value: 42 },
  { range: "11-21 d", value: 18 },
  { range: "22-49 d", value: 11 },
  { range: "50-89 d", value: 2 },
  { range: "90+ d", value: 1 },
];

export const xpDeliveredSeries = [
  { week: "Sem 1", rachas: 4200, posts: 1800, erp: 500 },
  { week: "Sem 2", rachas: 5400, posts: 2300, erp: 800 },
  { week: "Sem 3", rachas: 6900, posts: 2900, erp: 1200 },
  { week: "Sem 4", rachas: 8200, posts: 3400, erp: 1500 },
];

// KPIs por página
export const dashboardKpis = [
  { label: "Miembros activos", value: "284", context: "este mes", trend: { value: "+12%", direction: "up" as const } },
  { label: "Publicaciones", value: "1.842", context: "este mes", trend: { value: "+8%", direction: "up" as const } },
  { label: "Tasa participación", value: "67%", context: "semanal", trend: { value: "+22%", direction: "up" as const } },
  { label: "Inactivos >7d", value: "8", context: "requieren acción", trend: { value: "-3%", direction: "down" as const } },
];

export const streakKpis = [
  { label: "Racha más larga", value: "45", context: "", trend: { value: "+5", direction: "up" as const } },
  { label: "Miembros racha >7d", value: "142", context: "+12%", trend: { value: "+12%", direction: "up" as const } },
  { label: "Hitos del mes", value: "38", context: "logros alcanzados", trend: { value: "=0%", direction: "up" as const } },
  { label: "Rachas rotas", value: "6", context: "esta semana", trend: { value: "+2", direction: "up" as const } },
];

export const diagnosticKpis = [
  { label: "DM2", value: "148", context: "+8%", trend: { value: "+8%", direction: "up" as const } },
  { label: "Obesidad", value: "89", context: "+15%", trend: { value: "+15%", direction: "up" as const } },
  { label: "DM2+HTA", value: "31", context: "=0%", trend: { value: "=0%", direction: "up" as const } },
  { label: "Prediabetes", value: "16", context: "+3%", trend: { value: "+3%", direction: "up" as const } },
];

export const feedToday = {
  posts: 61,
  comments: 148,
  reactions: 392,
  nuevos: 3,
  rachasRotas: 2,
  xp: "12.840",
};

export const RISK_BY_MEMBER: Record<string, RiskLevel> = {
  "m-luis": "Alto",
  "m-rosa": "Medio",
  "m-manuel": "Medio",
  "m-teresa": "Bajo",
  "m-hector": "Bajo",
};
