"use client";

import { useState } from "react";
import { MoreHorizontal, Pencil, Plus, Search, Trash2, UserRound, UserRoundPlus, Eye, CalendarPlus, ClipboardPenLine, RefreshCw } from "lucide-react";
import { PageHeader } from "@/components/layout/page-header";
import { SectionHeader } from "@/components/layout/section-header";
import { StatusBadge } from "@/components/feedback/status-badge";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogMedia, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Input } from "@/components/ui/input";
import { Skeleton } from "@/components/ui/skeleton";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { usePatients } from "../hooks/use-patients";
import { PatientFormDialog } from "./patient-form-dialog";
import type { Patient, PatientInput } from "../types";

export function PatientsPage() {
  const { result, filters, loading, error, actionLoading, setFilters, setPage, save, remove, retry } = usePatients();
  const [formOpen, setFormOpen] = useState(false);
  const [editing, setEditing] = useState<Patient | undefined>();
  const [details, setDetails] = useState<Patient | undefined>();
  const [deleting, setDeleting] = useState<Patient | undefined>();

  const openCreate = () => { setEditing(undefined); setFormOpen(true); };
  const openEdit = (patient: Patient) => { setEditing(patient); setFormOpen(true); };
  const submit = async (input: PatientInput) => { await save(input, editing?.id); setFormOpen(false); };

  return <div className="flex flex-col gap-6 p-4 sm:p-6">
    <PageHeader title="Pacientes" description="Gestiona la información y el seguimiento de tus pacientes" icon={UserRound} actions={<Button size="sm" onClick={openCreate}><Plus data-icon="inline-start" />Nuevo paciente</Button>} />
    <div className="grid gap-3 sm:grid-cols-3">
      <Summary label="Pacientes activos" value={result ? String(result.total) : "—"} tone="primary" />
      <Summary label="Citas esta semana" value="24" tone="success" />
      <Summary label="Pendientes de completar" value="3" tone="warning" />
    </div>
    <section className="flex flex-col gap-4 rounded-2xl border border-border bg-card p-4 sm:p-5" aria-label="Filtros de pacientes">
      <div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="text-sm font-semibold">Directorio de pacientes</h2><p className="text-xs text-muted-foreground">Busca por nombre, documento o correo electrónico.</p></div><Button variant="outline" size="sm" onClick={retry} disabled={loading}><RefreshCw data-icon="inline-start" className={loading ? "animate-spin" : undefined} />Actualizar</Button></div>
      <div className="grid gap-3 md:grid-cols-[minmax(0,1fr)_180px_180px]">
        <div className="relative"><Search className="pointer-events-none absolute left-3 top-2.5 size-4 text-muted-foreground" /><Input className="pl-9" value={filters.search} onChange={(event) => setFilters({ search: event.target.value })} placeholder="Buscar paciente..." aria-label="Buscar pacientes" /></div>
        <select className="h-9 rounded-md border border-input bg-background px-3 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring" value={filters.status} onChange={(event) => setFilters({ status: event.target.value as typeof filters.status })} aria-label="Filtrar por estado"><option value="all">Todos los estados</option><option>Activo</option><option>Pendiente</option><option>Inactivo</option></select>
        <select className="h-9 rounded-md border border-input bg-background px-3 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring" value={filters.insurer} onChange={(event) => setFilters({ insurer: event.target.value })} aria-label="Filtrar por aseguradora"><option value="all">Todas las aseguradoras</option><option>SURA</option><option>Sanitas</option><option>Compensar</option><option>Particular</option><option>Famisanar</option></select>
      </div>
    </section>
    {loading ? <PatientsSkeleton /> : error ? <ErrorState message={error} onRetry={retry} /> : result?.data.length ? <PatientTable patients={result.data} onDetails={setDetails} onEdit={openEdit} onDelete={setDeleting} /> : <EmptyState onCreate={openCreate} />}
    {result && result.total > 0 && <Pagination page={result.page} totalPages={result.totalPages} onPageChange={setPage} />}
    <PatientFormDialog key={`${editing?.id ?? "new"}-${formOpen}`} open={formOpen} patient={editing} saving={actionLoading} onOpenChange={setFormOpen} onSubmit={submit} />
    <PatientDetails patient={details} onClose={() => setDetails(undefined)} />
    <AlertDialog open={Boolean(deleting)} onOpenChange={(open) => !open && setDeleting(undefined)}><AlertDialogContent><AlertDialogMedia className="bg-destructive-soft text-destructive"><Trash2 /></AlertDialogMedia><AlertDialogHeader><AlertDialogTitle>¿Eliminar paciente?</AlertDialogTitle><AlertDialogDescription>Se eliminará el registro de {deleting?.firstName} {deleting?.lastName}. Esta acción no se puede deshacer.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancelar</AlertDialogCancel><AlertDialogAction className="bg-destructive hover:bg-destructive/90" disabled={actionLoading} onClick={async () => { if (deleting) await remove(deleting.id); setDeleting(undefined); }}>Eliminar</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </div>;
}

function PatientTable({ patients, onDetails, onEdit, onDelete }: { patients: Patient[]; onDetails: (patient: Patient) => void; onEdit: (patient: Patient) => void; onDelete: (patient: Patient) => void }) {
  return <div className="flex flex-col gap-0 overflow-hidden rounded-2xl border border-border bg-card"><SectionHeader title={`${patients.length} pacientes visibles`} description="Directorio clínico" icon={UserRound} variant="primary" /><Table><TableHeader><TableRow><TableHead>Paciente</TableHead><TableHead>Documento</TableHead><TableHead className="hidden lg:table-cell">Contacto</TableHead><TableHead className="hidden md:table-cell">Aseguradora</TableHead><TableHead>Estado</TableHead><TableHead className="w-10"><span className="sr-only">Acciones</span></TableHead></TableRow></TableHeader><TableBody>{patients.map((patient) => <TableRow key={patient.id}><TableCell><button className="flex items-center gap-3 text-left" onClick={() => onDetails(patient)}><span className="flex size-9 shrink-0 items-center justify-center rounded-full bg-primary-soft text-xs font-bold text-primary">{patient.firstName[0]}{patient.lastName[0]}</span><span className="flex min-w-0 flex-col gap-0.5"><span className="truncate text-sm font-semibold text-foreground">{patient.firstName} {patient.lastName}</span><span className="text-xs text-muted-foreground">{patient.gender} · {getAge(patient.birthDate)} años</span></span></button></TableCell><TableCell><span className="text-sm font-medium">{patient.documentNumber}</span><span className="block text-xs text-muted-foreground">{patient.documentType}</span></TableCell><TableCell className="hidden lg:table-cell"><span className="block text-sm">{patient.phone}</span><span className="block max-w-44 truncate text-xs text-muted-foreground">{patient.email}</span></TableCell><TableCell className="hidden md:table-cell text-sm">{patient.insurer}</TableCell><TableCell><StatusBadge status={patient.status} color={statusColor(patient.status)} /></TableCell><TableCell><DropdownMenu><DropdownMenuTrigger render={<Button variant="ghost" size="icon-sm" aria-label={`Acciones de ${patient.firstName} ${patient.lastName}`} />}><MoreHorizontal /></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={() => onDetails(patient)}><Eye />Ver detalles</DropdownMenuItem><DropdownMenuItem onClick={() => onEdit(patient)}><Pencil />Editar</DropdownMenuItem><DropdownMenuItem><CalendarPlus />Agendar cita</DropdownMenuItem><DropdownMenuItem><ClipboardPenLine />Crear receta</DropdownMenuItem><DropdownMenuSeparator /><DropdownMenuItem className="text-destructive" onClick={() => onDelete(patient)}><Trash2 />Eliminar</DropdownMenuItem></DropdownMenuContent></DropdownMenu></TableCell></TableRow>)}</TableBody></Table></div>;
}

function PatientDetails({ patient, onClose }: { patient?: Patient; onClose: () => void }) {
  return <Dialog open={Boolean(patient)} onOpenChange={(open) => !open && onClose()}><DialogContent className="max-w-lg"><DialogHeader><DialogTitle>Detalle del paciente</DialogTitle><DialogDescription>Información registrada en el directorio.</DialogDescription></DialogHeader>{patient && <div className="flex flex-col gap-5"><div className="flex items-center gap-3 rounded-xl bg-primary-soft p-4"><span className="flex size-11 items-center justify-center rounded-full bg-primary text-sm font-bold text-white">{patient.firstName[0]}{patient.lastName[0]}</span><div><p className="font-semibold">{patient.firstName} {patient.lastName}</p><p className="text-xs text-muted-foreground">{patient.documentType} {patient.documentNumber}</p></div><div className="ml-auto"><StatusBadge status={patient.status} color={statusColor(patient.status)} /></div></div><div className="grid grid-cols-2 gap-x-4 gap-y-4 text-sm"><Detail label="Fecha de nacimiento" value={`${patient.birthDate} · ${getAge(patient.birthDate)} años`} /><Detail label="Teléfono" value={patient.phone} /><Detail label="Correo" value={patient.email || "No registrado"} /><Detail label="Aseguradora" value={patient.insurer} /><Detail label="Dirección" value={patient.address || "No registrada"} /><Detail label="Última cita" value={patient.lastAppointment ?? "Sin citas"} /></div><div className="rounded-lg border border-border p-3"><p className="mb-1 text-xs font-semibold text-muted-foreground">Observaciones</p><p className="text-sm">{patient.notes || "Sin observaciones."}</p></div></div>}</DialogContent></Dialog>;
}

function Detail({ label, value }: { label: string; value: string }) { return <div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-medium">{value}</p></div>; }
function Summary({ label, value, tone }: { label: string; value: string; tone: "primary" | "success" | "warning" }) { const colors = { primary: "bg-primary-soft text-primary", success: "bg-success-soft text-success-foreground", warning: "bg-warning-soft text-warning-foreground" }; return <div className="rounded-2xl border border-border bg-card p-4"><div className="flex items-center justify-between"><span className="text-xs font-medium text-muted-foreground">{label}</span><span className={`flex size-8 items-center justify-center rounded-lg ${colors[tone]}`}><UserRoundPlus className="size-4" /></span></div><p className="mt-3 text-2xl font-bold tracking-tight">{value}</p></div>; }
function PatientsSkeleton() { return <div className="rounded-2xl border border-border bg-card p-5">{Array.from({ length: 6 }).map((_, index) => <div className="flex items-center gap-4 border-b border-border py-4 last:border-0" key={index}><Skeleton className="size-9 rounded-full" /><div className="flex flex-1 flex-col gap-2"><Skeleton className="h-3.5 w-40" /><Skeleton className="h-3 w-24" /></div><Skeleton className="hidden h-4 w-28 md:block" /><Skeleton className="h-5 w-16 rounded-full" /></div>)}</div>; }
function EmptyState({ onCreate }: { onCreate: () => void }) { return <div className="flex flex-col items-center justify-center gap-3 rounded-2xl border border-dashed border-border bg-card py-16 text-center"><span className="flex size-12 items-center justify-center rounded-xl bg-primary-soft text-primary"><UserRound className="size-6" /></span><div><h3 className="text-sm font-semibold">No encontramos pacientes</h3><p className="mt-1 text-xs text-muted-foreground">Prueba con otros filtros o registra un nuevo paciente.</p></div><Button size="sm" onClick={onCreate}><Plus data-icon="inline-start" />Nuevo paciente</Button></div>; }
function ErrorState({ message, onRetry }: { message: string; onRetry: () => void }) { return <div className="flex flex-col items-center gap-3 rounded-2xl border border-destructive/20 bg-destructive-soft/40 py-14 text-center"><p className="text-sm font-semibold text-destructive">No pudimos cargar el directorio</p><p className="max-w-sm text-xs text-muted-foreground">{message}</p><Button variant="outline" size="sm" onClick={onRetry}><RefreshCw data-icon="inline-start" />Reintentar</Button></div>; }
function Pagination({ page, totalPages, onPageChange }: { page: number; totalPages: number; onPageChange: (page: number) => void }) { return <div className="flex items-center justify-between text-xs text-muted-foreground"><span>Página {page} de {totalPages}</span><div className="flex gap-2"><Button variant="outline" size="sm" disabled={page === 1} onClick={() => onPageChange(page - 1)}>Anterior</Button><Button variant="outline" size="sm" disabled={page === totalPages} onClick={() => onPageChange(page + 1)}>Siguiente</Button></div></div>; }
function getAge(date: string) { const birth = new Date(date); const today = new Date("2024-06-18"); let age = today.getFullYear() - birth.getFullYear(); if (today < new Date(today.getFullYear(), birth.getMonth(), birth.getDate())) age -= 1; return age; }
function statusColor(status: Patient["status"]) { const colors = { Activo: { bg: "var(--success-soft)", text: "var(--success-foreground)", dot: "var(--success-foreground)" }, Pendiente: { bg: "var(--warning-soft)", text: "var(--warning-foreground)", dot: "var(--warning)" }, Inactivo: { bg: "var(--destructive-soft)", text: "var(--destructive)", dot: "var(--destructive)" } }; return colors[status]; }
